import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export default function Page() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Recipe | {}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <h1 className="text-center font-bold text-4xl text-secondary">
          {router.query.slug}
        </h1>
      </main>
      <Footer />
    </>
  );
}
