import Head from "next/head";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
import NewRecipe from "@/components/newRecipe";
import PopularRecipe from "@/components/popularRecipe";
import Footer from "@/components/footer";
import { useEffect, useState } from "react";
import { axiosInstance } from "@/lib/axios";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);
  const [newRecipe, setNewRecipe] = useState([]);
  const [popularRecipe, setPopularRecipe] = useState([]);

  useEffect(() => {
    const getNewRecipe = async () => {
      const recipe = await axiosInstance.get("/recipe?sort=asc&limit=1&page=1");
      setNewRecipe(recipe.data?.data);
      setIsLoading(false);
    };
    getNewRecipe().catch(console.error);
  }, []);

  useEffect(() => {
    const getPopularRecipe = async () => {
      const recipe = await axiosInstance.get("/recipe?sort=asc&limit=6&page=1");
      setPopularRecipe(recipe.data?.data);
    };
    getPopularRecipe().catch(console.error);
  }, []);
  return (
    <>
      <Head>
        <title>Get The Best Recipe and Healty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <NewRecipe item={newRecipe} />
        <PopularRecipe item={popularRecipe} />
        <Footer />
      </main>
    </>
  );
}
